name: Deploy Node Application

on: 
  push:
    branches:
      - mern-ec2-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t integrationninjas/reactjs-app --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}'  .
      - name: Publish Image to docker hub
        run: docker push integrationninjas/reactjs-app:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull integrationninjas/reactjs-app:latest 
      - name: Delete old container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container integrationninjas/reactjs-app